### ISSUE TITLE
pibox-framebuffer invalid argument

### ISSUE THREAD

**Issue by tenox7** [kubesail/pibox-os#16]
Hello. Following instructions of how to install vanilla OS: https://docs.kubesail.com/guides/pibox/os/. In my case Rasperry PI OS Lite, latest version: `2022-09-22-raspios-bullseye-arm64-lite.img.xz`

When pibox-framebuffer service starts I get this:

```
Dec 11 03:21:25 raspberrypi systemd[1]: Started pibox-framebuffer.service.
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]: panic: open /dev/: is a directory
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]: goroutine 1 [running]:
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]: github.com/kubesail/pibox-framebuffer/pkg.(*PiboxFrameBuffer).openFrameBuffer(...)
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]:         /go/src/pibox-framebuffer/pkg/framebuffer.go:44
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]: github.com/kubesail/pibox-framebuffer/pkg.(*PiboxFrameBuffer).Splash(0x4000110ea0)
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]:         /go/src/pibox-framebuffer/pkg/framebuffer.go:313 +0x438
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]: main.main()
Dec 11 03:21:25 raspberrypi pibox-framebuffer[2036]:         /go/src/pibox-framebuffer/cmd/main.go:38 +0x20c
Dec 11 03:21:25 raspberrypi systemd[1]: pibox-framebuffer.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 11 03:21:25 raspberrypi systemd[1]: pibox-framebuffer.service: Failed with result 'exit-code'.
```

Thanks!

**Comment by tenox7** [comment]
it worked after a reboot also I should have opened this in https://github.com/kubesail/pibox-framebuffer/issues instead
